### ISSUE TITLE
Moodle 3.0+ requires $plugin->component property in version.php

### ISSUE THREAD

**Issue by bgwinner** [acoburn/moodle-block_vcl#1]
I don't know if you are still updating this, but I find it to be a great block, so I wanted to let you know about this requirement if you didn't already no.  Once I added the property the block installed perfectly.

[https://docs.moodle.org/dev/version.php](url)

**Comment by acoburn** [comment]
Resolved via https://github.com/acoburn/moodle-block_vcl/commit/920d4bd4f40f806d116f7f77d606609724291a31

**Comment by acoburn** [comment]
Thanks @bgwinner!
